name: 'Linting & test'

on: push

jobs:
  linting:
    name: 'Linting'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Install packages'
        run: npm install
      - name: 'Execute Lint'
        run: npm run lint
