name: 'Linting & test'

on: push

jobs:
  name: 'Linting'
  runs-on: ubuntu-latest
  steps: 
    - uses: actions/checkout@v4
      - name: 'Installs packages'
        run: npm install
      - name: 'Execute Later'
        run: npm run lint